name: EMERGENCY ACCESS (BREAK GLASS)
on:
  workflow_dispatch:
    inputs:
      crl_email:
        description: "CockroachLabs Email Address"
        required: true
        type: string
        
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - run: echo "expand this and look for 'env'."
      env:
        event: ${{ toJSON(github.event) }}

  foo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Always check out 'main'
        ref: main

    - name: Validate email address
      env:
        CRL_EMAIL: ${{ inputs.crl_email }}
      shell: bash
      run: |
        if [[ "$CRL_EMAIL" != *@cockroachlabs.com ]]; then
          echo "::error title='Invalid email'::Email address '$CRL_EMAIL' must end in '@cockroachlabs.com'"
          exit 1
        fi

    - name: Configure git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Define break glass ID
      id: breakglass_id
      run: echo breakglass_id=$(date +%F)-${{ github.triggering_actor }}-${{ github.run_id }} >> $GITHUB_ENV

    - name: Branch
      run: git switch --create breakglass/${{ env.breakglass_id }}

    - name: Add user
      run: |
        echo "# CRL user: ${{ inputs.crl_email }}" >> ./some/nested/config/users.yaml
        echo '"${{ env.breakglass_id }}": "breakglass-${{ env.breakglass_id }}"' >> ./some/nested/config/users.yaml

    - name: Commit
      run: "git commit -a -m 'BREAK GLASS: emergency access for @${{ github.triggering_actor }}'"

    - name: Push
      run: git push origin HEAD

    - name: Open PR
      run: |
        gh pr create \
          --head $(git branch --show-current) \
          --title "$(git show --format=%s)" \
          --body "Requested by @${{ github.triggering_actor }}." \
          --reviewer ${{ github.triggering_actor }} \
          --label "Break Glass"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
