name: "Build UI: Preview"
on:
  pull_request:
    branches:
      # TODO: change this to "master" when things stabilize
      - "main"
    paths: 
      - "the-ui/**"
jobs:
  build:
    name: "Preview Build"
    uses: "./.github/workflows/reusable--build-ui.yaml"
    with:
      the_build_id: ${{ github.event.pull_request.number }}
      build_type: "preview"
