name: "Build UI: Preview"
on:
  pull_request:
    branches:
      # TODO: change this to "master" when things stabilize
      - "main"
    paths: 
      - "the-ui/**"
jobs:
  debug:
    runs-on: "ubuntu-latest"
    steps:
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: echo "Expand this and look at 'env'."

  build:
    name: "Preview Build"
    uses: "./.github/workflows/reusable--build-ui.yaml"
    secrets: {}
    with:
      the_build_id: ${{ github.event.pull_request.number }}
      build_type: "preview"

  upload:
    uses: "./.github/workflows/reusable--upload-build.yaml"
    needs: build
    permissions:
      deployments: "write"
      id-token: "write"
      issues: "write"
      contents: "read"
      repository-projects: "write"
      pull-requests: "write"
    with:
      the_build_id: ${{ github.event.pull_request.number }}
      build_type: "preview"
