name: "UI General: Build"
on:
  push:
    branches-ignore:
      # TODO: change to master
      - "main"
      - "release-*"
    paths: 
      - "the-ui/**"
jobs:
  build:
    name: "General Build"
    uses: "./.github/workflows/reusable_ui-build.yaml"
    with:
      the_build_id: ${{ github.sha }}
      build_type: "other"
