name: "Delete Preview Deployments"
on:
  pull_request_target:
    branches:
      - "main"
    types: 
      - "closed"
    paths:
      - "the-ui/**"
jobs:
  delete_deployments:
    name: "Delete deployments"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Delete deployments"
      uses: "actions/github-script@v6"
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          ["staging", "prod"].forEach(async (cc_env) => {
            const deployments = github.paginate.iterator(github.rest.repos.listDeployments, {
              owner: owner,
              repo: repo,
              environment: `UI Previews (${cc_env} backend)`,
            });

            for await (const page of deployments) {
              for (const deployment of page.data) {
                if (deployment.payload.pr_number !== ${{ github.event.pull_request.number }}) {
                  continue;
                }

                core.info(`deactivating and deleting deployment ID '${deployment.id}'`)
                await github.rest.repos.createDeploymentStatus({
                  owner: owner,
                  repo: repo,
                  deployment_id: deployment.id,
                  state: "inactive",
                  auto_inactive: false
                });

                await github.rest.repos.deleteDeployment({
                  owner: owner,
                  repo: repo,
                  deployment_id: deployment.id,
                });
              }
            }
          });
