name: "Destroy Preview Deployments"
on:
  pull_request_target:
    branches:
      - "main"
    types: 
      - "closed"
    paths:
      - "the-ui/**"
jobs:
  debug:
    runs-on: "ubuntu-latest"
    steps:
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: echo $EVENT_CONTEXT

  destroy_deployments:
    name: "Delete deployments"
    runs-on: "ubuntu-latest"
    # DEBUG: does this fix the "can't delete an environment" issue?
    permissions: "write-all"
    steps:
    - name: "Delete deployments"
      uses: "actions/github-script@v6"
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          ["staging", "prod"].forEach(async (cc_env) => {
            const envName = `PR #${process.env.PR_NUMBER} (${cc_env} backend)`;
            let deployments = await github.rest.repos.listDeployments({
              owner: owner,
              repo: repo,
              environment: envName,
            });

            console.log("DBG: deployments = ", deployments);

            deployments.data.forEach(async (deployment) => {
              await github.rest.repos.createDeploymentStatus({
                owner: owner,
                repo: repo,
                deployment_id: deployment.id,
                state: "inactive",
                auto_inactive: true
              });

              await github.rest.repos.deleteDeployment({
                owner: owner,
                repo: repo,
                deployment_id: deployment.id,
              });
            });

            await github.rest.repos.deleteAnEnvironment({
              owner: owner,
              repo: repo,
              environment_name: envName,
            });
          });
