name: "UI Preview: Build"
on:
  pull_request:
    branches:
      # TODO: change this to "master" when things stabilize
      - "main"
    paths: 
      - "the-ui/**"
jobs:
  debug:
    runs-on: "ubuntu-latest"
    steps:
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: echo "Expand this and look at 'env'."

  build:
    name: "Preview Build"
    uses: "./.github/workflows/reusable_ui-build.yaml"
    secrets: {}
    with:
      the_build_id: ${{ github.event.pull_request.number }}
      build_type: "preview"
