name: "Upload Build: Staging"
permissions:
  actions: "read"
  packages: "read"
  repository-projects: "read"
  security-events: "read"
  statuses: "read"
  contents: "read"
  issues: "write"
  pull-requests: "write"
  deployments: "write"
on:
  workflow_run:
    workflows: [ "Build UI: Staging" ]
    types: [ "completed" ]
jobs:
  upload:
    uses: "./.github/workflows/reusable--upload-build.yaml"
    with:
      the_build_id: ${{ github.event.workflow_run.pull_requests[0].number }}
      build_type: "staging"
