name: "Staging: Upload UI"
on:
  workflow_run:
    workflows: [ "Staging: Build UI" ]
    types: [ "completed" ]
jobs:
  debug:
    runs-on: "ubuntu-latest"
    steps:
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
        sha: github.sha
        head_sha: github.head_sha
      run: echo "Expand this and look at 'env'."

  upload:
    uses: "./.github/workflows/reusable--upload-build.yaml"
    with:
      the_build_id: ${{ github.event.workflow_run.pull_requests[0].number }}
      build_type: "staging"
