name: "Upload Build: Preview"
permissions:
  actions: "read"
  packages: "read"
  repository-projects: "read"
  security-events: "read"
  statuses: "read"
  contents: "read"
  issues: "write"
  pull-requests: "write"
  deployments: "write"
on:
  workflow_run:
    workflows: [ "Build UI: Preview" ]
    types: [ "completed" ]
jobs:
  debug:
    runs-on: "ubuntu-latest"
    steps:
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: echo $EVENT_CONTEXT

  upload:
    uses: "./.github/workflows/reusable--upload-build.yaml"
    with:
      the_build_id: ${{ github.event.workflow_run.pull_requests[0].number }}
      build_type: "preview"
